# Site settings
title: Gintaras Jomantas
email: gjomantas@albany.edu
description: Gintaras is INF Major from Long Island
url: http://gj648183.github.io
github_username: gj648183

# Build settings
markdown: kramdown
permalink: pretty
